"use client";
import { useCallback, useEffect, useState } from "react";
type FeedEvent={id:number;at:string;label:string;detail:string;kind:"info"|"success"|"warning"};
type TabletState={connected:boolean;device?:string;model?:string;android?:string;foregroundPackage?:string;sandboxForeground:boolean;route?:string;updatedAt:string;events:FeedEvent[];test?:{status:"idle"|"running"|"passed"|"failed";step?:string;error?:string}};
const BRIDGE="http://localhost:3131";
export default function Home(){
 const[state,setState]=useState<TabletState|null>(null),[bridgeOnline,setBridgeOnline]=useState(false),[lastError,setLastError]=useState(""),[imageTick,setImageTick]=useState(0),[starting,setStarting]=useState(false),[launching,setLaunching]=useState(false);
 const refresh=useCallback(async()=>{try{const response=await fetch(BRIDGE+"/state",{cache:"no-store"});if(!response.ok)throw new Error();const next=(await response.json())as TabletState;setState(next);setBridgeOnline(true);setLastError("");if(next.connected)setImageTick(Date.now())}catch{setBridgeOnline(false);setLastError("Local tablet monitor is not running")}},[]);
 useEffect(()=>{refresh();const timer=window.setInterval(refresh,1500);return()=>window.clearInterval(timer)},[refresh]);
 const connected=bridgeOnline&&Boolean(state?.connected),events=state?.events??[];
 const canRun=connected&&state?.sandboxForeground&&state.route==="/home"&&state.test?.status!=="running";
 const runWorkout=async()=>{setStarting(true);try{const response=await fetch(BRIDGE+"/run-workout",{method:"POST"});if(!response.ok)throw new Error();await refresh()}catch{setLastError("Could not start the workout test")}finally{setStarting(false)}};
 const runVideoClass=async()=>{setStarting(true);try{const response=await fetch(BRIDGE+"/run-video-class",{method:"POST"});if(!response.ok)throw new Error();await refresh()}catch{setLastError("Could not start the video class test")}finally{setStarting(false)}};
 const runMonument=async()=>{setStarting(true);try{const response=await fetch(BRIDGE+"/run-monument",{method:"POST"});if(!response.ok)throw new Error();await refresh()}catch{setLastError("Could not start the Monument test")}finally{setStarting(false)}};
 const launchSand=async()=>{setLaunching(true);setLastError("");try{const response=await fetch(BRIDGE+"/launch-sand",{method:"POST"});if(!response.ok)throw new Error();window.setTimeout(refresh,1200)}catch{setLastError("Could not launch Sandbox")}finally{window.setTimeout(()=>setLaunching(false),1200)}};
 const currentLabel=!bridgeOnline?"Waiting for VC TestBench monitor":!connected?"Tablet disconnected":state?.sandboxForeground?(state.route?"Sandbox visible · "+state.route:"Sandbox is open"):"Tablet connected · Sandbox not in foreground";
 const activeTest=state?.test?.status==="running"?state.test.name:"";
 return <main className="shell">
  <header className="topbar"><div className="brand-mark">VC</div><div><p className="eyebrow">VERSACLIMBER AUTOMATION</p><h1>VC TestBench</h1></div><button className="launch-sand" disabled={!connected||launching} onClick={launchSand}>{launching?"Launching…":"Launch Sand"}</button><div className={"device-pill "+(connected?"connected":"disconnected")}><span className="online-dot"/>{connected?"Lenovo tablet connected":"Tablet disconnected"}</div></header>
  <section className="hero-card"><div><p className="eyebrow">ACTUAL TABLET STATUS</p><h2>{currentLabel}</h2><p className="subtitle">{connected?(state?.model??"Lenovo tablet")+" · Android "+(state?.android??"—")+" · "+(state?.device??"USB"):"Reconnect USB debugging to resume the live feed"}</p></div><div className={"status-badge "+(connected?(state?.sandboxForeground?"running":"success"):"ready")}><span/>{connected?(state?.sandboxForeground?"APP VISIBLE":"CONNECTED"):"OFFLINE"}</div><div className="progress-track"><div style={{width:connected?"100%":"0%"}}/></div><div className="hero-footer"><span>{events.length} confirmed tablet events</span><span>{state?.updatedAt?new Date(state.updatedAt).toLocaleTimeString():"No live update"}</span></div></section>
  <div className="flowbar"><div className="flow-actions"><button className={"secondary "+(activeTest==="Workout smoke test"?"active":"")} disabled={!canRun||starting} onClick={runWorkout}>Workout smoke</button><button className={"secondary "+(activeTest==="Monument smoke test"?"active":"")} disabled={!canRun||starting} onClick={runMonument}>Monument smoke</button><button className={"secondary "+(activeTest==="Video class test"?"active":"")} disabled={!canRun||starting} onClick={runVideoClass}>{activeTest==="Video class test"?"Test running…":starting?"Starting…":"Video class to 45 ft"}</button></div><button className="secondary refresh-button" onClick={refresh}>Refresh</button></div>
  <div className="content-grid">
   <section className="panel timeline-panel"><div className="panel-heading"><div><p className="eyebrow">REALTIME FEED</p><h3>Confirmed actions and screen changes</h3></div><span className={"live-label "+(connected?"":"offline")}><i/>{connected?"LIVE":"OFFLINE"}</span></div><div className="timeline">{!events.length&&<div className="empty-feed"><div className="empty-icon">◎</div><strong>No tablet activity yet</strong><span>VC TestBench will only show events it confirms on the real device.</span></div>}{[...events].reverse().map((event,index)=><div className={"step passed "+event.kind} key={event.id}><div className="step-marker">{index===0&&connected?"●":"✓"}</div><div className="step-copy"><strong>{event.label}</strong><span>{event.detail}</span></div><div className="step-time">{event.at}</div></div>)}</div></section>
   <aside className="right-column"><section className="panel tablet-panel"><div className="panel-heading compact"><div><p className="eyebrow">LIVE TABLET VIEW</p><h3>{state?.sandboxForeground?"Sandbox app":"Lenovo tablet"}</h3></div><span className={"recording-dot "+(connected?"":"offline-dot")}/></div><div className={"live-screen "+(connected?"":"screen-offline")}>{connected?<img src={BRIDGE+"/screen?t="+imageTick} alt="Current Lenovo tablet screen"/>:<div><span>USB</span><strong>Tablet disconnected</strong><small>Reconnect and authorize USB debugging</small></div>}</div><p className="capture-note">{connected?"This image is captured from the tablet and refreshes automatically.":"No cached image is shown while the tablet is offline."}</p></section><section className="metrics-row"><div><span>USB STATUS</span><strong>{connected?"Online":"Offline"}</strong></div><div><span>APP STATE</span><strong>{state?.sandboxForeground?"Visible":"—"}</strong></div><div><span>ROUTE</span><strong>{state?.route??"—"}</strong></div></section></aside>
  </div>
  <footer className="actionbar"><div><span className="shield">{connected?"✓":"!"}</span><p><strong>{state?.test?.status==="running"?(state.test.step??"Test running"):state?.test?.status==="passed"?(state.test.name??"Test")+" passed":connected?"Choose a real test sequence":"No tablet control active"}</strong><small>{lastError||state?.test?.error||"Only verified tablet actions appear in the feed"}</small></p></div></footer>
 </main>
}
